name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rayees786/new-react:latest
    - name: Push the Docker Image
      run: docker login  -u rayees786 -p ${{secrets.NEW_REACT_APP_TOKEN}} && docker push rayees786/new-react:latest
